packages:
  - 'packages/*'
  # This Cloudflare Worker is managed with npm (has its own package-lock.json),
  # so excluding it avoids pnpm workspace/lockfile mismatches in CI.
  - '!packages/wordbook-counter-worker'
onlyBuiltDependencies:
  - esbuild
  - msw
