apiVersion: zeabur.com/v1
kind: Template
metadata:
  name: Danci
spec:
  description: 基于 AMAS 自适应学习引擎的智能单词学习应用
  icon: https://raw.githubusercontent.com/Heartcoolman/vocabulary-learning-app/dev/packages/frontend/public/favicon.svg
  tags:
    - Tool
    - Website
  readme: |-
    # Danci - 智能单词学习应用

    基于 AMAS 自适应学习引擎的智能单词学习应用。

    ## 功能特点
    - AMAS 自适应学习引擎
    - 视觉疲劳检测
    - 学习数据统计分析

    ## 部署说明
    1. 部署完成后为 Backend 服务绑定域名
    2. 将 Backend 域名填入 BACKEND_DOMAIN 变量
    3. 重新部署 Frontend 服务

  variables:
    - key: PUBLIC_DOMAIN
      type: DOMAIN
      name: Frontend Domain
      description: Frontend public domain
    - key: BACKEND_DOMAIN
      type: STRING
      name: Backend Domain
      description: Backend public domain (e.g., api.example.com)
    - key: JWT_SECRET
      type: STRING
      name: JWT Secret
      description: JWT signing key (64+ chars)

  services:
    - name: PostgreSQL
      template: PREBUILT
      spec:
        source:
          image: postgres:15
        ports:
          - id: database
            port: 5432
            type: TCP
        volumes:
          - id: data
            dir: /var/lib/postgresql/data
        env:
          POSTGRES_DB:
            default: danci
          POSTGRES_USER:
            default: danci
          POSTGRES_PASSWORD:
            default: ${PASSWORD}
            expose: true
          POSTGRES_URI:
            default: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${CONTAINER_HOSTNAME}:5432/${POSTGRES_DB}
            expose: true

    - name: Redis
      template: PREBUILT
      spec:
        source:
          image: redis:7-alpine
        ports:
          - id: cache
            port: 6379
            type: TCP
        volumes:
          - id: data
            dir: /data
        env:
          REDIS_URI:
            default: redis://${CONTAINER_HOSTNAME}:6379
            expose: true

    - name: Backend
      template: GIT
      spec:
        source:
          source: GITHUB
          repo: 1100646679
          branch: dev
        dockerfile: packages/backend-rust/Dockerfile
        ports:
          - id: web
            port: 3000
            type: HTTP
        volumes:
          - id: data
            dir: /app/data
        env:
          HOST:
            default: '0.0.0.0'
          PORT:
            default: '3000'
          RUST_LOG:
            default: info
          DATABASE_URL:
            default: ${PostgreSQL.POSTGRES_URI}
          REDIS_URL:
            default: ${Redis.REDIS_URI}
          JWT_SECRET:
            default: ${JWT_SECRET}
          CORS_ORIGIN:
            default: https://${PUBLIC_DOMAIN}

    - name: Frontend
      template: GIT
      domainKey: PUBLIC_DOMAIN
      spec:
        source:
          source: GITHUB
          repo: 1100646679
          branch: dev
        dockerfile: Dockerfile.zeabur-frontend
        ports:
          - id: web
            port: 80
            type: HTTP
        env:
          VITE_API_URL:
            default: https://${BACKEND_DOMAIN}
