apiVersion: zeabur.com/v1
kind: Template
metadata:
  name: Danci
spec:
  description: 基于 AMAS 自适应学习引擎的智能单词学习应用
  icon: https://raw.githubusercontent.com/Heartcoolman/vocabulary-learning-app/dev/packages/frontend/public/favicon.svg
  tags:
    - Tool
    - Website
  readme: |-
    # Danci - 智能单词学习应用

    基于 AMAS 自适应学习引擎的智能单词学习应用。

    ## 功能特点
    - AMAS 自适应学习引擎
    - 视觉疲劳检测
    - 学习数据统计分析

  variables:
    - key: PUBLIC_DOMAIN
      type: DOMAIN
      name: Domain
      description: Frontend domain
    - key: JWT_SECRET
      type: STRING
      name: JWT Secret
      description: JWT signing key (64+ chars)

  services:
    - name: PostgreSQL
      template: PREBUILT
      spec:
        source:
          image: postgres:15
        ports:
          - id: database
            port: 5432
            type: TCP
        volumes:
          - id: data
            dir: /var/lib/postgresql/data
        env:
          POSTGRES_DB:
            default: danci
          POSTGRES_USER:
            default: danci
          POSTGRES_PASSWORD:
            default: ${PASSWORD}
            expose: true
          POSTGRES_URI:
            default: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${CONTAINER_HOSTNAME}:5432/${POSTGRES_DB}
            expose: true

    - name: Redis
      template: PREBUILT
      spec:
        source:
          image: redis:7-alpine
        ports:
          - id: cache
            port: 6379
            type: TCP
        volumes:
          - id: data
            dir: /data
        env:
          REDIS_URI:
            default: redis://${CONTAINER_HOSTNAME}:6379
            expose: true

    - name: Backend
      template: GIT
      spec:
        source:
          source: GITHUB
          repo: 1100646679
          branch: dev
          subPath: packages/backend-rust
        ports:
          - id: web
            port: 3000
            type: HTTP
        volumes:
          - id: data
            dir: /app/data
        env:
          HOST:
            default: '0.0.0.0'
          PORT:
            default: '3000'
          RUST_LOG:
            default: info
          DATABASE_URL:
            default: ${POSTGRES_URI}
          REDIS_URL:
            default: ${REDIS_URI}
          JWT_SECRET:
            default: ${JWT_SECRET}
          CORS_ORIGIN:
            default: https://${PUBLIC_DOMAIN}
      dependencies:
        - PostgreSQL
        - Redis

    - name: Frontend
      template: GIT
      domainKey: PUBLIC_DOMAIN
      spec:
        source:
          source: GITHUB
          repo: 1100646679
          branch: dev
          subPath: packages/frontend
        ports:
          - id: web
            port: 80
            type: HTTP
        env:
          VITE_API_URL:
            default: https://${ZEABUR_BACKEND_URL}
      dependencies:
        - Backend
