apiVersion: zeabur.com/v1
kind: Template
metadata:
  name: Danci
spec:
  description: 基于 AMAS 自适应学习引擎的智能单词学习应用
  icon: https://raw.githubusercontent.com/Heartcoolman/vocabulary-learning-app/dev/packages/frontend/public/favicon.svg
  coverImage: https://raw.githubusercontent.com/Heartcoolman/vocabulary-learning-app/dev/docs/images/cover.png
  tags:
    - Education
    - Tool
  readme: |
    # Danci - 智能单词学习应用

    基于 AMAS 自适应学习引擎的智能单词学习应用。

    ## 功能特点
    - AMAS 自适应学习引擎
    - 视觉疲劳检测
    - 学习数据统计分析
    - 词库管理

  variables:
    - key: PUBLIC_DOMAIN
      type: DOMAIN
      name: 应用域名
      description: 前端应用访问域名
    - key: JWT_SECRET
      type: STRING
      name: JWT 密钥
      description: JWT 签名密钥

  services:
    # PostgreSQL (使用 Zeabur Marketplace)
    - name: postgresql
      template: PREBUILT
      spec:
        id: postgresql
        name: PostgreSQL
        icon: https://raw.githubusercontent.com/zeabur/service-icons/main/marketplace/postgresql.svg
        source:
          image: postgres:15
        ports:
          - id: database
            port: 5432
            type: TCP
        volumes:
          - id: data
            dir: /var/lib/postgresql/data
        env:
          POSTGRES_DB:
            default: danci
          POSTGRES_USER:
            default: danci
          POSTGRES_PASSWORD:
            default: ${PASSWORD}
            expose: true
          POSTGRES_URI:
            default: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${CONTAINER_HOSTNAME}:5432/${POSTGRES_DB}
            expose: true
            readonly: true

    # Redis (使用 Zeabur Marketplace)
    - name: redis
      template: PREBUILT
      spec:
        id: redis
        name: Redis
        icon: https://raw.githubusercontent.com/zeabur/service-icons/main/marketplace/redis.svg
        source:
          image: redis:7-alpine
        ports:
          - id: cache
            port: 6379
            type: TCP
        volumes:
          - id: data
            dir: /data
        env:
          REDIS_URI:
            default: redis://${CONTAINER_HOSTNAME}:6379
            expose: true
            readonly: true

    # Rust 后端
    - name: backend
      template: GIT
      icon: https://www.rust-lang.org/logos/rust-logo-512x512.png
      spec:
        source:
          type: GITHUB
          repoID: 1100646679
          branch: dev
          subPath: packages/backend-rust
        ports:
          - id: web
            port: 3000
            type: HTTP
        volumes:
          - id: data
            dir: /app/data
        env:
          HOST:
            default: '0.0.0.0'
          PORT:
            default: '3000'
          RUST_LOG:
            default: info
          DATABASE_URL:
            default: ${postgresql.POSTGRES_URI}
          REDIS_URL:
            default: ${redis.REDIS_URI}
          JWT_SECRET:
            default: ${JWT_SECRET}
          CORS_ORIGIN:
            default: https://${PUBLIC_DOMAIN}
      dependencies:
        - postgresql
        - redis

    # 前端
    - name: frontend
      template: GIT
      icon: https://vitejs.dev/logo.svg
      domainKey: PUBLIC_DOMAIN
      spec:
        source:
          type: GITHUB
          repoID: 1100646679
          branch: dev
          subPath: packages/frontend
        ports:
          - id: web
            port: 80
            type: HTTP
        env:
          VITE_API_URL:
            default: https://${backend.ZEABUR_WEB_DOMAIN}
      dependencies:
        - backend
