/* auto-generated by NAPI-RS */
/* eslint-disable */
/** 因果推断 Native 实现 */
export declare class CausalInferenceNative {
  /** 创建新的因果推断实例 */
  constructor(featureDim: number, config?: CausalInferenceConfig | undefined | null);
  /** 训练倾向得分模型（逻辑回归 + 梯度下降 + L2正则化） */
  fitPropensity(observations: Array<CausalObservation>): void;
  /**
   * 训练结果模型（Ridge回归 + Cholesky分解）
   * 分别训练处理组和对照组模型
   */
  fitOutcome(observations: Array<CausalObservation>): void;
  /** 完整拟合（倾向得分 + 结果模型） */
  fit(observations: Array<CausalObservation>): void;
  /**
   * 计算 AIPW 双重稳健估计
   * 公式: tau = (1/n) * sum[ mu1(X) - mu0(X) + T(Y-mu1(X))/e(X) - (1-T)(Y-mu0(X))/(1-e(X)) ]
   */
  estimateAte(observations: Array<CausalObservation>): CausalEstimate;
  /** Bootstrap 标准误估计（使用 Rayon 并行化） */
  bootstrapSe(
    observations: Array<CausalObservation>,
    nBootstrap?: number | undefined | null,
  ): number;
  /** 诊断倾向得分分布 */
  diagnosePropensity(observations: Array<CausalObservation>): PropensityDiagnostics;
  /** 获取倾向得分（自动添加截距项） */
  getPropensityScore(features: Float64Array): number;
  /** 预测结果（自动添加截距项） */
  predictOutcome(features: Float64Array, treatment: number): number;
  /** 检查是否已拟合 */
  isFitted(): boolean;
  /** 获取特征维度 */
  getFeatureDim(): number;
  /** 重置模型 */
  reset(): void;
}

/** Action 结构体 */
export interface Action {
  wordId: string;
  difficulty: string;
  scheduledAt?: number;
}

/** ActionSelection 结构体 - 动作选择结果 */
export interface ActionSelection {
  selectedIndex: number;
  selectedAction: Action;
  exploitation: number;
  exploration: number;
  score: number;
  allScores: Array<number>;
}

/** ActionSelectionTyped 结构体 - 类型化动作选择结果 */
export interface ActionSelectionTyped {
  selectedIndex: number;
  selectedAction: ActionTyped;
  exploitation: number;
  exploration: number;
  score: number;
  allScores: Array<number>;
}

/** Action 类型化版本 */
export interface ActionTyped {
  wordId: string;
  difficulty: Difficulty;
  scheduledAt?: number;
}

/** BanditModel 结构体 (字段命名与 TS 对齐) */
export interface BanditModel {
  aMatrix: Array<number>;
  b: Array<number>;
  lMatrix: Array<number>;
  lambda: number;
  alpha: number;
  d: number;
  updateCount: number;
}

/** 因果效应估计结果 */
export interface CausalEstimate {
  /** 平均处理效应 */
  ate: number;
  /** 标准误 */
  standardError: number;
  /** 95% 置信区间下限 */
  confidenceIntervalLower: number;
  /** 95% 置信区间上限 */
  confidenceIntervalUpper: number;
  /** 样本量 */
  sampleSize: number;
  /** 有效样本量（IPW加权后） */
  effectiveSampleSize: number;
  /** p值 */
  pValue: number;
  /** 是否显著（alpha=0.05） */
  significant: boolean;
}

/** 因果推断配置 */
export interface CausalInferenceConfig {
  /** 倾向得分截断下限 */
  propensityMin?: number;
  /** 倾向得分截断上限 */
  propensityMax?: number;
  /** 学习率 */
  learningRate?: number;
  /** 正则化系数 */
  regularization?: number;
  /** 最大迭代次数 */
  maxIterations?: number;
  /** 收敛阈值 */
  convergenceThreshold?: number;
}

/** 因果观测数据 */
export interface CausalObservation {
  /** 特征向量 */
  features: Array<number>;
  /** 处理组标记 (0 或 1) */
  treatment: number;
  /** 结果值 */
  outcome: number;
  /** 时间戳（可选） */
  timestamp?: number;
  /** 用户ID（可选） */
  userId?: string;
}

/** DiagnosticResult 结构体 - 诊断结果 */
export interface DiagnosticResult {
  isHealthy: boolean;
  hasNan: boolean;
  hasInf: boolean;
  conditionNumber: number;
  minDiagonal: number;
  maxDiagonal: number;
  message: string;
}

/** Difficulty 枚举 */
export declare const enum Difficulty {
  Recognition = 0,
  Recall = 1,
  Spelling = 2,
  Listening = 3,
  Usage = 4,
}

/** LinUCBContext 结构体 */
export interface LinUcbContext {
  timeOfDay: number;
  dayOfWeek: number;
  sessionDuration: number;
  fatigueFactor?: number;
}

/** 倾向得分诊断 */
export interface PropensityDiagnostics {
  /** 均值 */
  mean: number;
  /** 标准差 */
  std: number;
  /** 中位数 */
  median: number;
  /** 处理组均值 */
  treatmentMean: number;
  /** 对照组均值 */
  controlMean: number;
  /** 重叠度量 */
  overlap: number;
  /** AUC（区分度） */
  auc: number;
}

/** UCBStats 结构体 - UCB 统计信息 */
export interface UcbStats {
  theta: Array<number>;
  exploitation: number;
  confidence: number;
  score: number;
}

/** UserState 结构体 */
export interface UserState {
  masteryLevel: number;
  recentAccuracy: number;
  studyStreak: number;
  totalInteractions: number;
  averageResponseTime: number;
}
