/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** 记忆痕迹 */
export interface MemoryTrace {
  /** 时间戳（秒） */
  timestamp: number
  /** 是否正确回答 */
  isCorrect: boolean
}
/** ACT-R 状态 */
export interface ActrState {
  /** 衰减率 d (默认 0.5) */
  decay: number
  /** 回忆阈值 τ */
  threshold: number
  /** 噪声缩放 s */
  noiseScale: number
  /** 更新计数 */
  updateCount: number
}
/** 因果观测数据 */
export interface CausalObservation {
  /** 特征向量 */
  features: Array<number>
  /** 处理组标记 (0 或 1) */
  treatment: number
  /** 结果值 */
  outcome: number
}
/** 因果效应估计结果 */
export interface CausalEstimate {
  /** 平均处理效应 */
  ate: number
  /** 标准误 */
  standardError: number
  /** 95% 置信区间下限 */
  ciLower: number
  /** 95% 置信区间上限 */
  ciUpper: number
  /** 样本量 */
  sampleSize: number
  /** p值 */
  pValue: number
  /** 是否显著 */
  significant: boolean
}
/** 倾向得分诊断 */
export interface PropensityDiagnostics {
  mean: number
  std: number
  treatmentMean: number
  controlMean: number
  overlap: number
}
/** Beta 分布参数 */
export interface BetaParams {
  alpha: number
  beta: number
}
/** BanditModel 结构体 (字段命名与 TS 对齐) */
export interface BanditModel {
  A: Array<number>
  b: Array<number>
  L: Array<number>
  lambda: number
  alpha: number
  d: number
  updateCount: number
}
/** Difficulty 枚举 */
export const enum Difficulty {
  Recognition = 0,
  Recall = 1,
  Spelling = 2,
  Listening = 3,
  Usage = 4
}
/** Action 结构体 */
export interface Action {
  wordId: string
  difficulty: string
  scheduledAt?: number
}
/** Action 类型化版本 */
export interface ActionTyped {
  wordId: string
  difficulty: Difficulty
  scheduledAt?: number
}
/** UserState 结构体 */
export interface UserState {
  masteryLevel: number
  recentAccuracy: number
  studyStreak: number
  totalInteractions: number
  averageResponseTime: number
}
/** LinUCBContext 结构体 */
export interface LinUcbContext {
  timeOfDay: number
  dayOfWeek: number
  sessionDuration: number
  fatigueFactor?: number
}
/** ActionSelection 结构体 - 动作选择结果 */
export interface ActionSelection {
  selectedIndex: number
  selectedAction: Action
  exploitation: number
  exploration: number
  score: number
  allScores: Array<number>
}
/** ActionSelectionTyped 结构体 - 类型化动作选择结果 */
export interface ActionSelectionTyped {
  selectedIndex: number
  selectedAction: ActionTyped
  exploitation: number
  exploration: number
  score: number
  allScores: Array<number>
}
/** UCBStats 结构体 - UCB 统计信息 */
export interface UcbStats {
  theta: Array<number>
  exploitation: number
  confidence: number
  score: number
}
/** DiagnosticResult 结构体 - 诊断结果 */
export interface DiagnosticResult {
  isHealthy: boolean
  hasNaN: boolean
  hasInf: boolean
  conditionNumber: number
  minDiagonal: number
  maxDiagonal: number
  message: string
}
export type ACTRMemoryNative = ActrMemoryNative
/** ACT-R 记忆模型 Native 实现 */
export declare class ActrMemoryNative {
  constructor(decay?: number | undefined | null, threshold?: number | undefined | null, noiseScale?: number | undefined | null)
  /** 计算激活度: A = ln(Σ w_j · t_j^(-d)) */
  computeActivation(traces: Array<MemoryTrace>, currentTime: number): number
  /** 计算回忆概率: P = 1 / (1 + exp(-(A-τ)/s)) */
  retrievalProbability(activation: number): number
  /** 计算个性化衰减率 */
  computePersonalizedDecay(memoryFactor: number, speedFactor: number, stabilityFactor: number): number
  /** 获取状态 */
  getState(): ActrState
  /** 设置状态 */
  setState(state: ActrState): void
}
/** 因果推断 Native 实现 */
export declare class CausalInferenceNative {
  constructor(featureDim: number)
  /** 训练倾向得分模型（逻辑回归） */
  fitPropensity(observations: Array<CausalObservation>): void
  /** 计算 AIPW 双重稳健估计 */
  estimateAte(observations: Array<CausalObservation>): CausalEstimate
  /** Bootstrap 标准误估计 */
  bootstrapSe(observations: Array<CausalObservation>, nBootstrap: number): number
  /** 诊断倾向得分 */
  diagnosePropensity(observations: Array<CausalObservation>): PropensityDiagnostics
}
export type LinUCBNative = LinUcbNative
/** LinUCB 原生实现 */
export declare class LinUcbNative {
  /** 创建新的 LinUCB 实例 */
  constructor(alpha?: number | undefined | null, lambda?: number | undefined | null)
  /** 选择动作（类型化版本，性能更优） */
  selectActionTyped(state: UserState, actions: Array<ActionTyped>, context: LinUCBContext): ActionSelectionTyped
  /** 选择动作 */
  selectAction(state: UserState, actions: Array<Action>, context: LinUCBContext): ActionSelection
  /** 批量选择动作 */
  selectActionBatch(states: Array<UserState>, actionsList: Array<Array<Action>>, contexts: Array<LinUCBContext>): Array<ActionSelection>
  /** 更新模型 */
  update(state: UserState, action: Action, reward: number, context: LinUCBContext): void
  /** 使用 Float64Array 更新（零拷贝） */
  updateWithFloat64Array(featureVec: Float64Array, reward: number): void
  /** 使用特征向量更新 */
  updateWithFeatureVector(featureVec: Array<number>, reward: number): void
  /** 批量更新 */
  updateBatch(featureVecs: Array<Array<number>>, rewards: Array<number>): number
  /** 健康诊断 */
  diagnose(): DiagnosticResult
  /** 自检 */
  selfTest(): boolean
  /** 获取模型 */
  getModel(): BanditModel
  /** 设置模型 */
  setModel(model: BanditModel): void
  /** 重置模型 */
  reset(): void
  /** 获取 alpha */
  get alpha(): number
  /** 设置 alpha */
  set alpha(value: number)
  /** 获取更新计数 */
  get updateCount(): number
  /** 计算冷启动 alpha */
  static getColdStartAlpha(interactionCount: number, recentAccuracy: number, fatigue: number): number
}
/** Thompson Sampling Native 实现 */
export declare class ThompsonSamplingNative {
  constructor()
  /** 采样 Beta 分布 */
  sampleBeta(alpha: number, beta: number): number
  /** 批量采样 */
  batchSample(actionKeys: Array<string>): Array<number>
  /** 更新参数 */
  update(actionKey: string, success: boolean): void
  /** 获取动作的期望值 */
  getExpectedValue(actionKey: string): number
  /** 带上下文的批量采样 */
  batchSampleWithContext(contextKey: string, actionKeys: Array<string>): Array<number>
  /** 带上下文的更新参数 */
  updateWithContext(contextKey: string, actionKey: string, success: boolean): void
  /** 获取带上下文的期望值 */
  getExpectedValueWithContext(contextKey: string, actionKey: string): number
  /** 获取全局参数 */
  getGlobalParams(actionKey: string): BetaParams | null
  /** 设置全局参数 */
  setGlobalParams(actionKey: string, alpha: number, beta: number): void
  /** 重置所有参数 */
  reset(): void
  /** 获取所有动作的统计信息 */
  getAllStats(): Record<string, BetaParams>
}
