/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** BanditModel 结构体 (字段命名与 TS 对齐) */
export interface BanditModel {
  A: Array<number>
  b: Array<number>
  L: Array<number>
  lambda: number
  alpha: number
  d: number
  updateCount: number
}
/** Difficulty 枚举 */
export const enum Difficulty {
  Recognition = 0,
  Recall = 1,
  Spelling = 2,
  Listening = 3,
  Usage = 4
}
/** Action 结构体 */
export interface Action {
  wordId: string
  difficulty: string
  scheduledAt?: number
}
/** Action 类型化版本 */
export interface ActionTyped {
  wordId: string
  difficulty: Difficulty
  scheduledAt?: number
}
/** UserState 结构体 */
export interface UserState {
  masteryLevel: number
  recentAccuracy: number
  studyStreak: number
  totalInteractions: number
  averageResponseTime: number
}
/** LinUCBContext 结构体 */
export interface LinUcbContext {
  timeOfDay: number
  dayOfWeek: number
  sessionDuration: number
  fatigueFactor?: number
}
/** ActionSelection 结构体 - 动作选择结果 */
export interface ActionSelection {
  selectedIndex: number
  selectedAction: Action
  exploitation: number
  exploration: number
  score: number
  allScores: Array<number>
}
/** UCBStats 结构体 - UCB 统计信息 */
export interface UcbStats {
  theta: Array<number>
  exploitation: number
  confidence: number
  score: number
}
/** DiagnosticResult 结构体 - 诊断结果 */
export interface DiagnosticResult {
  isHealthy: boolean
  hasNaN: boolean
  hasInf: boolean
  conditionNumber: number
  minDiagonal: number
  maxDiagonal: number
  message: string
}
export type LinUCBNative = LinUcbNative
/** LinUCB 原生实现 */
export declare class LinUcbNative {
  /** 创建新的 LinUCB 实例 */
  constructor(alpha?: number | undefined | null, lambda?: number | undefined | null)
  /** 选择动作 */
  selectAction(state: UserState, actions: Array<Action>, context: LinUCBContext): ActionSelection
  /** 更新模型 */
  update(state: UserState, action: Action, reward: number, context: LinUCBContext): void
  /** 使用 Float64Array 更新（零拷贝） */
  updateWithFloat64Array(featureVec: Float64Array, reward: number): void
  /** 使用特征向量更新 */
  updateWithFeatureVector(featureVec: Array<number>, reward: number): void
  /** 批量更新 */
  updateBatch(featureVecs: Array<Array<number>>, rewards: Array<number>): number
  /** 健康诊断 */
  diagnose(): DiagnosticResult
  /** 自检 */
  selfTest(): boolean
  /** 获取模型 */
  getModel(): BanditModel
  /** 设置模型 */
  setModel(model: BanditModel): void
  /** 重置模型 */
  reset(): void
  /** 获取 alpha */
  get alpha(): number
  /** 设置 alpha */
  set alpha(value: number)
  /** 获取更新计数 */
  get updateCount(): number
  /** 计算冷启动 alpha */
  static getColdStartAlpha(interactionCount: number, recentAccuracy: number, fatigue: number): number
}
